name: build
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - .github/workflows/build.yml
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
     contents: read
     packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Set date
        id: date
        run: |
          echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - id: string
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repo }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@master
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@master
        env:
          CONTEXT: ${{ github.workflow }}
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/${{ steps.string.outputs.lowercase }}:${{ env.date }}
            ghcr.io/${{ steps.string.outputs.lowercase }}:latest
            ${{ steps.string.outputs.lowercase }}:${{ env.date }}
            ${{ steps.string.outputs.lowercase }}:latest